version: 2.1
references:
  default_docker_ruby_executor: &default_docker_ruby_executor
    image: circleci/ruby:2.7.1-node-browsers
    environment:
      BUNDLE_PATH: vendor/bundle
      PGHOST: 127.0.0.1
      PGUSER: land
      RAILS_ENV: test
      COVERAGE: true
      TZ: /usr/share/zoneinfo/America/Chicago
  postgres: &postgres
    image: circleci/postgres:11.4-alpine
    environment:
      POSTGRES_DB: land_test
      POSTGRES_USER: land

jobs:
  build:
    working_directory: ~/land/land_index
    docker:
      - *default_docker_ruby_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - land-
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: Bundle Install
          command: |
            gem install bundler
            bundle check || bundle install
      - save_cache:
          key: land-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/land/land_index/node_modules
            - ~/land/land_index/vendor/bundle

  test:
    working_directory: ~/land/land_index
    parallelism: 1
    docker:
      - *default_docker_ruby_executor
      - *postgres
    steps:
      - checkout
      - restore_cache:
          keys:
            - land-
      - run:
          name: Bundle Install
          command: |
            gem install bundler
            bundle check || bundle install
      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Install postgresql-client
          command: sudo apt install -y postgresql-client || true
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: |
            bundle exec rails db:setup --trace
      - run:
          name: Run RSpec (headless)
          command: |
            mkdir /tmp/test-results
            ./cc-test-reporter before-build
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
      - run:
          name: Code Climate Test Coverage
          command: |
            ./cc-test-reporter format-coverage -t simplecov -o "coverage/codeclimate.$CIRCLE_NODE_INDEX.json"
      - persist_to_workspace:
          root: coverage
          paths:
            - codeclimate.*.json
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  upload-coverage:
    working_directory: ~/land/land_index
    docker:
      - *default_docker_ruby_executor
    environment:
      CC_TEST_REPORTER_ID: 6aa31a8c5421bb710854bc69f9a7d8d48492125de2a76ebdbc50f6167d9cc748
    steps:
      - attach_workspace:
          at: ~/land/land_index
      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Combine and Upload Coverage
          command: |
            ./cc-test-reporter sum-coverage --output - codeclimate.*.json | ./cc-test-reporter upload-coverage --debug --input -
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - upload-coverage:
          requires:
             - test
